import { createContext, useContext, useState } from "react";

type Language = "en" | "am";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    websiteName: "TUMBI",
    home: "Home",
    categories: "Categories",
    productsAndServices: "Products & Services",
    browseCompanies: "Browse Companies",
    favorites: "Favorites",
    about: "About",
    login: "Login",
    register: "Register",
    logout: "Logout",
    editProfile: "Edit Profile",
    registerCompany: "Register a Company",
    searchMaterials: "Search for materials...",
    findQualityMaterials: "Find Quality Construction Materials",
    popularCategories: "Popular Categories",
    recentlyAdded: "Recently Added Materials",
    addProduct: "Add Product",
    filters: "Filters",
    priceRange: "Price Range",
    category: "Category",
    unit: "Unit",
    location: "Location",
    sortBy: "Sort By",
    latest: "Latest",
    priceLowHigh: "Price: Low to High",
    priceHighLow: "Price: High to Low",
    applyFilters: "Apply Filters",
    resetFilters: "Reset",
    viewDetails: "View Details",
    edit: "Edit",
    delete: "Delete",
    cement: "Cement",
    steel: "Steel",
    wood: "Wood",
    tiles: "Tiles",
    paint: "Paint",
    other: "Other",
    browseJobs: "Browse Jobs",
    postJob: "Post a Job",
    browseProductsAndServices: "Browse Products & Services",
    browseProducts: "Browse Products",
    steelRebar: "Steel Rebar",
    blocks: "Blocks",
    hcb: "HCB",
    bricks: "Bricks",
    hydraform: "Hydraform",
    gypsum: "Gypsum",
    gypsumPowder: "Gypsum Powder",
    gypsumBlock: "Gypsum Block",
    gypsumBoard: "Gypsum Board",
    accessories: "Accessories",
    hinges: "Hinges",
    nails: "Nails",
    screws: "Screws",
    aluminium: "Aluminium",
    glass: "Glass",
    scaffoldings: "Scaffoldings",
    electricMaterials: "Electric materials",
    sanitaryMaterial: "Sanitary material",
    metals: "Metals",
    rhs: "RHS",
    chs: "CHS",
    ltz: "LTZ",
    metalSheets: "Metal sheets",
    roofing: "Roofing",
    tools: "Tools",
    powerTools: "Power tools",
    nonPowerTools: "Non-power tools",
    chemicals: "Chemicals",
    doors: "Doors",
    stones: "Stones",
    marble: "Marble",
    granite: "Granite",
    search: "Search",
    tenders: "Tenders",
    newTenders: "New Tenders",
    mostTalkedAboutArticles: "Most Talked About Articles",
    recentlyAddedCompanies: "Recently Added Companies",
    viewAllTenders: "View All Tenders",
    viewAllProducts: "View All Products",
    viewAllArticles: "View All Articles",
    viewAllCompanies: "View All Companies",
    notSpecified: "Not specified",
    clickToViewFullTenderDocument: "Click to view full tender document.",
    articles: "Articles",
    navigation: "Navigation",
    language: "Language",
    addNewProduct: "Add New Product",
    editProduct: "Edit Product",
    addProductDescription: "Add a new construction material to your catalog",
    updateProductInformation: "Update product information",
    authenticationRequired: "Authentication Required",
    pleaseLogInToAddProduct: "Please log in to add a new product.",
    goToLogin: "Go to Login",
    loading: "Loading...",
    companyRegistrationRequired: "Company Registration Required",
    registerCompanyBeforeAddingProducts: "You need to register a company before you can add products.",
    productImages: "Product Images (up to 3)",
    clickToUploadProductImages: "Click to upload product images",
    productName: "Product Name",
    categoryIsRequired: "Category is required",
    company: "Company",
    selectCompany: "Select company",
    selectCategory: "Select category",
    priceETB: "Price (ETB)",
    priceIsRequired: "Price is required",
    unitIsRequired: "Unit is required",
    stockQuantity: "Stock Quantity",
    description: "Description",
    descriptionIsRequired: "Description is required",
    cancel: "Cancel",
    saving: "Saving...",
    addProductButton: "Add Product",
    saveChanges: "Save Changes",
    registerCompanyButton: "Register Company",
    productNameIsRequired: "Product name is required",
    youCanUploadMaxImages: "You can upload a maximum of 3 images (including existing ones).",
    youMustBeLoggedInToAddProduct: "You must be logged in to add a product.",
    failedToSaveProduct: "Failed to save product",
    productAddedSuccessfully: "Product added successfully.",
    productUpdatedSuccessfully: "Product updated successfully.",
    anErrorOccurredWhileSavingProduct: "An error occurred while saving the product",
    registerNewCompany: "Register New Company",
    editCompany: "Edit Company",
    registerCompanyDescription: "Register your construction materials company",
    updateCompanyInformation: "Update your company information",
    companyLogo: "Company Logo",
    clickToUploadCompanyLogo: "Click to upload company logo",
    error: "Error",
    companyName: "Company Name",
    companyNameIsRequired: "Company name is required",
    companyNameMinLength: "Company name must be at least 2 characters",
    email: "Email",
    emailIsRequired: "Email is required",
    invalidEmailAddress: "Invalid email address",
    phone: "Phone",
    phoneIsRequired: "Phone is required",
    invalidPhoneNumberFormat: "Invalid phone number format",
    locationIsRequired: "Location is required",
    locationMinLength: "Location must be at least 2 characters",
    website: "Website",
    companyType: "Company Type",
    loadingTypes: "Loading types...",
    selectCompanyType: "Select company type",
    descriptionMinLength: "Description must be at least 10 characters",
    describeCompanyPlaceholder: "Describe your company, services, and expertise in construction materials...",
    registering: "Registering...",
    companyRegisteredSuccessfully: "Company registered successfully.",
    companyUpdatedSuccessfully: "Company updated successfully.",
    failedToCreateCompany: "Failed to create company.",
    serverReturnedInvalidResponse: "Server returned invalid response",
    anErrorOccurredWhileCreatingCompany: "An error occurred while creating the company",
    pleaseUploadAnImageFile: "Please upload an image file",
    imageSizeLessThan2MB: "Image size should be less than 2MB",
    postNewJob: "Post New Job",
    editJob: "Edit Job",
    fillOutJobDetails: "Fill out the job details below",
    updateJobDetails: "Update job details",
    jobTitle: "Job Title",
    jobTitleRequired: "Job title is required",
    jobTitlePlaceholder: "e.g. Senior Construction Engineer",
    jobDescription: "Job Description",
    jobDescriptionRequired: "Job description is required",
    jobDescriptionPlaceholder: "Describe the job responsibilities, requirements, and benefits...",
    locationRequired: "Location is required",
    locationPlaceholder: "e.g. Addis Ababa, Ethiopia",
    jobType: "Job Type",
    selectJobType: "Select job type",
    fullTime: "Full-time",
    partTime: "Part-time",
    contract: "Contract",
    temporary: "Temporary",
    internship: "Internship",
    categoryPlaceholder: "e.g. Engineering, Construction",
    position: "Position",
    positionPlaceholder: "e.g. Senior Engineer",
    experience: "Experience",
    experiencePlaceholder: "e.g. 5+ years",
    deadline: "Deadline",
    requiredSkills: "Required Skills",
    requiredSkillsPlaceholder: "List the required skills...",
    qualifications: "Qualifications",
    qualificationsPlaceholder: "List the required qualifications...",
    howToApply: "How to Apply",
    howToApplyPlaceholder: "Instructions on how to apply...",
    additionalNotes: "Additional Notes",
    additionalNotesPlaceholder: "Any additional information...",
    salary: "Salary",
    salaryPlaceholder: "e.g. 50,000 ETB/month",
    applicationLink: "Application Link",
    applicationLinkPlaceholder: "https://company.com/apply",
    youMustBeLoggedInToPostJob: "You must be logged in to post a job.",
    jobPostedSuccessfully: "Job posted successfully.",
    jobUpdatedSuccessfully: "Job updated successfully.",
    failedToCreateJob: "Failed to create job",
    failedToUpdateJob: "Failed to update job",
    addTender: "Add Tender",
    addNewTender: "Add New Tender",
    title: "Title",
    closingDate: "Closing Date",
    openingDate: "Opening Date",
    region: "Region",
    publishedDate: "Published Date",
    featured: "Featured",
    tenderDetail: "Tender Detail",
    eligibilityCriteria: "Eligibility Criteria",
    requiredDocuments: "Required Documents",
    bidDocumentPrice: "Bid Document Price",
    bidBond: "Bid Bond",
    contactInformation: "Contact Information",
    createTender: "Create Tender",
    pickClosingDate: "Pick a closing date",
    pickOpeningDate: "Pick an opening date",
    pickPublishedDate: "Pick a published date",
  },
  am: {
    websiteName: "ቱምቢ",
    home: "ቤት",
    categories: "ምድቦች",
    productsAndServices: "ምርቶች እና አገልግሎቶቶች",
    browseCompanies: "ኩባንያዎችን ያስሱ",
    favorites: "የተወደዱ",
    about: "ስለ እኛ",
    login: "ግባ",
    register: "ይመዝገቡ",
    logout: "ውጣ",
    editProfile: "መገለጫን ያስተካክሉ",
    registerCompany: "ኩባንያ ያስመዝግቡ",
    searchMaterials: "ቁሳቁሶችን ይፈልጉ...",
    findQualityMaterials: "ጥራት ያለው የግንባታ እቃዎች ያግኙ",
    popularCategories: "ታዋቂ ምድቦች",
    recentlyAdded: "በቅርቡ የተጨመሩ እቃዎች",
    addProduct: "ምርት ጨምር",
    filters: "ማጣሪያዎች",
    priceRange: "የዋጋ ክልል",
    category: "ምድብ",
    unit: "መለኪያ",
    location: "አድራሻ",
    sortBy: "ደርድር በ",
    latest: "የቅርብ ጊዜ",
    priceLowHigh: "ዋጋ: ዝቅተኛ ወደ ከፍተኛ",
    priceHighLow: "ዋጋ: ከፍተኛ ወደ ዝቅተኛ",
    applyFilters: "ማጣሪያዎችን ተግብር",
    resetFilters: "ዳግም አስጀምር",
    viewDetails: "ዝርዝሮችን ይመልከቱ",
    edit: "አርትዕ",
    delete: "ሰርዝ",
    cement: "ሲሚንቶ",
    steel: "ብረት",
    wood: "እንጨት",
    tiles: "ሰሌዳዎች",
    paint: "ቀለም",
    other: "ሌላ",
    browseJobs: "ስራዎችን ያስሱ",
    postJob: "ስራ ይለጥፉ",
    browseProductsAndServices: "ምርቶችን እና አገልግሎቶችን ያስሱ",
    browseProducts: "ምርቶችን ያስሱ",
    steelRebar: "የብረት ዘንግ",
    blocks: "ብሎኮች",
    hcb: "ኤች.ሲ.ቢ",
    bricks: "ጡቦች",
    hydraform: "ሃይድራፎርም",
    gypsum: "ጂፕሰም",
    gypsumPowder: "የጂፕሰም ዱቄት",
    gypsumBlock: "የጂፕሰም ቦርድ",
    gypsumBoard: "የጂፕሰም ቦርድ",
    accessories: "መለዋወጫዎች",
    hinges: "ማጠፊያዎች",
    nails: "ምስማሮች",
    screws: "ስፒውሮች",
    aluminium: "አልሙኒየም",
    glass: "መስታወት",
    scaffoldings: "ስካፎልዲንግ",
    electricMaterials: "የኤሌክትሪክ ዕቃዎች",
    sanitaryMaterial: "የቧንቧና ባኞ ቤት ዕቃዎች",
    metals: "ብረቶች",
    rhs: "አር.ኤች.ኤስ",
    chs: "ሲ.ኤች.ኤስ",
    ltz: "ኤል.ቲ.ዜድ",
    metalSheets: "የብረት ሉሆች",
    roofing: "የጣሪያ ስራ",
    tools: "መሳሪያዎች",
    powerTools: "የኃይል መሣሪያዎች",
    nonPowerTools: "ኃይል የሌላቸው መሣሪያዎች",
    chemicals: "ኬሚካሎች",
    doors: "በሮች",
    stones: "ድንጋዮች",
    marble: "እብነ በረድ",
    granite: "ግራናይት",
    search: "ፈልግ",
    tenders: "ጨረታዎች",
    newTenders: "አዲስ ጨረታዎች",
    mostTalkedAboutArticles: "በጣም የተነጋገሩባቸው ጽሑፎች",
    recentlyAddedCompanies: "በቅርቡ የተጨመሩ ኩባንያዎች",
    viewAllTenders: "ሁሉንም ጨረታዎች ይመልከቱ",
    viewAllProducts: "ሁሉንም ምርቶች ይመልከቱ",
    viewAllArticles: "ሁሉንም ጽሑፎች ይመልከቱ",
    viewAllCompanies: "ሁሉንም ኩባንያዎች ይመልከቱ",
    notSpecified: "አልተገለጸም",
    clickToViewFullTenderDocument: "ሙሉ የጨረታ ሰነድ ለማየት ይጫኑ።",
    articles: "ጽሑፎች",
    navigation: "አሰሳ",
    language: "ቋንቋ",
    addNewProduct: "አዲስ ምርት ጨምር",
    editProduct: "ምርት አርትዕ",
    addProductDescription: "አዲስ የግንባታ እቃዎች ወደ ካታሎግዎ ያክሉ",
    updateProductInformation: "የምርት መረጃን ያዘምኑ",
    authenticationRequired: "ማረጋገጫ ያስፈልጋል",
    pleaseLogInToAddProduct: "አዲስ ምርት ለመጨመር እባክዎ ይግቡ።",
    goToLogin: "ወደ መግቢያ ይሂዱ",
    loading: "በመጫን ላይ...",
    companyRegistrationRequired: "የኩባንያ ምዝገባ ያስፈልጋል",
    registerCompanyBeforeAddingProducts: "ምርቶችን ከመጨመርዎ በፊት ኩባንያ መመዝገብ አለብዎት።",
    productImages: "የምርት ምስሎች (እስከ 3)",
    clickToUploadProductImages: "የምርት ምስሎችን ለመስቀል ይጫኑ",
    productName: "የምርት ስም",
    categoryIsRequired: "ምድብ ያስፈልጋል",
    company: "ኩባንያ",
    selectCompany: "ኩባንያ ይምረጡ",
    selectCategory: "ምድብ ይምረጡ",
    priceETB: "ዋጋ (ETB)",
    priceIsRequired: "ዋጋ ያስፈልጋል",
    unitIsRequired: "መለኪያ ያስፈልጋል",
    stockQuantity: "የክምችት ብዛት",
    description: "መግለጫ",
    descriptionIsRequired: "መግለጫ ያስፈልጋል",
    cancel: "ይቅር",
    saving: "በማስቀመጥ ላይ...",
    addProductButton: "ምርት ጨምር",
    saveChanges: "ለውጦችን አስቀምጥ",
    registerCompanyButton: "ኩባንያ ይመዝግቡ",
    productNameIsRequired: "የምርት ስም ያስፈልጋል",
    youCanUploadMaxImages: "ከፍተኛው 3 ምስሎችን መስቀል ይችላሉ (ነባር ምስሎችን ጨምሮ)።",
    youMustBeLoggedInToAddProduct: "ምርት ለመጨመር መግባት አለብዎት።",
    failedToSaveProduct: "ምርቱን ማስቀመጥ አልተሳካም።",
    productAddedSuccessfully: "ምርት በተሳካ ሁኔታ ታክሏል።",
    productUpdatedSuccessfully: "ምርት በተሳካ ሁኔታ ታድሷል።",
    anErrorOccurredWhileSavingProduct: "ምርቱን በሚያስቀምጡበት ጊዜ ስህተት ተከስቷል።",
    registerNewCompany: "አዲስ ኩባንያ ይመዝገቡ",
    editCompany: "ኩባንያ አርትዕ",
    registerCompanyDescription: "የግንባታ እቃዎች ኩባንያዎን ያስመዝግቡ",
    updateCompanyInformation: "የኩባንያዎን መረጃ ያዘምኑ",
    companyLogo: "የኩባንያ አርማ",
    clickToUploadCompanyLogo: "የኩባንያ አርማ ለመስቀል ይጫኑ",
    error: "ስህተት",
    companyName: "የኩባንያ ስም",
    companyNameIsRequired: "የኩባንያ ስም ያስፈልጋል",
    companyNameMinLength: "የኩባንያ ስም ቢያንስ 2 ፊደላት መሆን አለበት",
    email: "ኢሜይል",
    emailIsRequired: "ኢሜይል ያስፈልጋል",
    invalidEmailAddress: "ልክ ያልሆነ የኢሜይል አድራሻ",
    phone: "ስልክ",
    phoneIsRequired: "ስልክ ያስፈልጋል",
    invalidPhoneNumberFormat: "ልክ ያልሆነ የስልክ ቁጥር ቅርጸት",
    locationIsRequired: "አድራሻ ያስፈልጋል",
    locationMinLength: "አድራሻ ቢያንስ 2 ፊደላት መሆን አለበት",
    website: "ድር ጣቢያ",
    companyType: "የኩባንያ ዓይነት",
    loadingTypes: "ዓይነቶችን በመጫን ላይ...",
    selectCompanyType: "የኩባንያ ዓይነት ይምረጡ",
    descriptionMinLength: "መግለጫ ቢያንስ 10 ፊደላት መሆን አለበት",
    describeCompanyPlaceholder: "ኩባንያዎን፣ አገልግሎቶችዎን እና የግንባታ እቃዎች እውቀትዎን ይግለጹ...",
    registering: "በመመዝገብ ላይ...",
    companyRegisteredSuccessfully: "ኩባንያ በተሳካ ሁኔታ ተመዝግቧል።",
    companyUpdatedSuccessfully: "ኩባንያ በተሳካ ሁኔታ ታድሷል።",
    failedToCreateCompany: "ኩባንያ መፍጠር አልተሳካም።",
    serverReturnedInvalidResponse: "አገልጋዩ ልክ ያልሆነ ምላሽ ሰጥቷል",
    anErrorOccurredWhileCreatingCompany: "ኩባንያውን በሚፈጥሩበት ጊዜ ስህተት ተከስቷል።",
    pleaseUploadAnImageFile: "እባክዎ የምስል ፋይል ይስቀሉ",
    imageSizeLessThan2MB: "የምስል መጠን ከ 2 ሜባ ያነሰ መሆን አለበት",
    postNewJob: "አዲስ ሥራ ይለጥፉ",
    editJob: "ሥራ አርትዕ",
    fillOutJobDetails: "የሥራ ዝርዝሮችን ያስቀምጡ",
    updateJobDetails: "የሥራ ዝርዝሮችን ያዘምኑ",
    jobTitle: "የሥራ ርዕስ",
    jobTitleRequired: "የሥራ ርዕስ ያስፈልጋል",
    jobTitlePlaceholder: "ለምሳሌ፣ የግንባታ ኢንጂነር ላይ",
    jobDescription: "የሥራ መግለጫ",
    jobDescriptionRequired: "የሥራ መግለጫ ያስፈልጋል",
    jobDescriptionPlaceholder: "የሥራ ተግባሮችን፣ መስፈርቶችን እና ጥቅሞችን ይግለጹ...",
    locationRequired: "አድራሻ ያስፈልጋል",
    locationPlaceholder: "ለምሳሌ፣ አዲስ አበባ፣ ኢትዮጵያ",
    jobType: "የሥራ ዓይነት",
    selectJobType: "የሥራ ዓይነት ይምረጡ",
    fullTime: "ሙሉ ጊዜ",
    partTime: "ከእጅ በላይ",
    contract: "የቅጥር",
    temporary: "ጊዜያዊ",
    internship: "የተማሪ ስራ",
    categoryPlaceholder: "ለምሳሌ፣ ኢንጂነሪንግ፣ ግንባታ",
    position: "አቅጣጫ",
    positionPlaceholder: "ለምሳሌ፣ ላይ ኢንጂነር",
    experience: "ልምድ",
    experiencePlaceholder: "ለምሳሌ፣ 5+ ዓመታት",
    deadline: "የመጨረሻ ቀን",
    requiredSkills: "የሚፈለጉ ሊለውዎች",
    requiredSkillsPlaceholder: "የሚፈለጉ ሊለውዎችን ይዘርዝሩ...",
    qualifications: "ብቃቶች",
    qualificationsPlaceholder: "የሚፈለጉ ብቃቶችን ይዘርዝሩ...",
    howToApply: "እንዴት መለጠፍ እንደሚቻል",
    howToApplyPlaceholder: "መለጠፍ እንዴት እንደሚቻል መመሪያ...",
    additionalNotes: "ተጨማሪ ማስታወሻዎች",
    additionalNotesPlaceholder: "ማንኛውም ተጨማሪ መረጃ...",
    salary: "ደመወዝ",
    salaryPlaceholder: "ለምሳሌ፣ 50,000 ETB/በወር",
    applicationLink: "የመለጠፍ አገናኝ",
    applicationLinkPlaceholder: "https://company.com/apply",
    youMustBeLoggedInToPostJob: "ሥራ ለመለጠፍ መግባት አለብዎት።",
    jobPostedSuccessfully: "ሥራ በተሳካ ሁኔታ ተለጠፈ።",
    jobUpdatedSuccessfully: "ሥራ በተሳካ ሁኔታ ተሻሻለ።",
    failedToCreateJob: "ሥራ መፍጠር አልተሳካም",
    failedToUpdateJob: "ሥራ ለማሻሻል አልተሳካም",
    addTender: "ጨረታ ጨምር",
    addNewTender: "አዲስ ጨረታ ጨምር",
    title: "ርዕስ",
    closingDate: "የመዝጊያ ቀን",
    openingDate: "የመክፈቻ ቀን",
    region: "ክልል",
    publishedDate: "የታተመበት ቀን",
    featured: "ተለይቶ የቀረበ",
    tenderDetail: "የጨረታ ዝርዝር",
    eligibilityCriteria: "የብቃት መስፈርት",
    requiredDocuments: "የሚያስፈልጉ ሰነዶች",
    bidDocumentPrice: "የጨረታ ሰነድ ዋጋ",
    bidBond: "የጨረታ ማስከበሪያ",
    contactInformation: "የእውቂያ መረጃ",
    createTender: "ጨረታ ፍጠር",
    pickClosingDate: "የመዝጊያ ቀን ይምረጡ",
    pickOpeningDate: "የመክፈቻ ቀን ይምረጡ",
    pickPublishedDate: "የታተመበት ቀን ይምረጡ",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "am" : "en"));
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
